# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterIsochrones
                                 A QGIS plugin
 Create isochrones from elevation or other raster map data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-21
        copyright            : (C) 2019 by Geographisches Institut, Universität Zürich
        email                : gereon.kaiping@geo.uzh.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterIsochrones class from file RasterIsochrones.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rasterisochrones import RasterIsochrones
    return RasterIsochrones(iface)
